language: c

sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu
  - cd docker
  - ./run.sh
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=jstarcher/siege
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

script:
  - docker run --rm -t jstarcher/siege -c1 -r1 jstarcher.com
