language: c

sudo: required

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull ubuntu
  - cd docker
  - ./run.sh
  - export REPO=jstarcher/siege
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TAG .
  - docker push $REPO

script:
  - docker run --rm -t jstarcher/siege -c1 -r1 jstarcher.com
