#!/usr/bin/perl
use Pod::Man;
my $input   = $ARGV[0] or barf();
my $output  = $ARGV[1] or barf();
my $name    = $ARGV[2] or barf();
my $section = $ARGV[3] or barf();

my $parser = Pod::Man->new (release => $VERSION, center => $name, section => $section, release => 'JoeDog');
$parser->parse_from_file ($input, $output);

sub barf() {
  print "usage: $0 <file.pod> <file.1> <section[num]>\n";
  exit(1);
}
